apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: policySet.idql.io
spec:
  group: idql.io
  scope: Cluster
  names:
    plural: policySet
    singular: policy
    kind: policySet
    shortNames:
      - ps
  versions:
    - name: v1beta1
      # Each version can be enabled/disabled using served flag
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            metadata:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
            spec:
              type: object
              properties:
                policies:
                  type: array
                  items:
                    $ref: "https://github.com/independentid/IDQL-specs/schema/idql.schema.json"
